/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for ArchiveStrategy
 */
public class ArchiveStrategyTest {
    private final ArchiveStrategy model = new ArchiveStrategy();

    /**
     * Model tests for ArchiveStrategy
     */
    @Test
    public void testArchiveStrategy() {
        // TODO: test ArchiveStrategy
    }

    /**
     * Test the property 'none'
     */
    @Test
    public void noneTest() {
        // TODO: test none
    }

    /**
     * Test the property 'tar'
     */
    @Test
    public void tarTest() {
        // TODO: test tar
    }

    /**
     * Test the property 'zip'
     */
    @Test
    public void zipTest() {
        // TODO: test zip
    }

}
