/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for ArtifactLocation
 */
public class ArtifactLocationTest {
    private final ArtifactLocation model = new ArtifactLocation();

    /**
     * Model tests for ArtifactLocation
     */
    @Test
    public void testArtifactLocation() {
        // TODO: test ArtifactLocation
    }

    /**
     * Test the property 'archiveLogs'
     */
    @Test
    public void archiveLogsTest() {
        // TODO: test archiveLogs
    }

    /**
     * Test the property 'artifactory'
     */
    @Test
    public void artifactoryTest() {
        // TODO: test artifactory
    }

    /**
     * Test the property 'azure'
     */
    @Test
    public void azureTest() {
        // TODO: test azure
    }

    /**
     * Test the property 'gcs'
     */
    @Test
    public void gcsTest() {
        // TODO: test gcs
    }

    /**
     * Test the property 'git'
     */
    @Test
    public void gitTest() {
        // TODO: test git
    }

    /**
     * Test the property 'hdfs'
     */
    @Test
    public void hdfsTest() {
        // TODO: test hdfs
    }

    /**
     * Test the property 'http'
     */
    @Test
    public void httpTest() {
        // TODO: test http
    }

    /**
     * Test the property 'oss'
     */
    @Test
    public void ossTest() {
        // TODO: test oss
    }

    /**
     * Test the property 'raw'
     */
    @Test
    public void rawTest() {
        // TODO: test raw
    }

    /**
     * Test the property 's3'
     */
    @Test
    public void s3Test() {
        // TODO: test s3
    }

}
