/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for ArtifactGC
 */
public class ArtifactGCTest {
    private final ArtifactGC model = new ArtifactGC();

    /**
     * Model tests for ArtifactGC
     */
    @Test
    public void testArtifactGC() {
        // TODO: test ArtifactGC
    }

    /**
     * Test the property 'podMetadata'
     */
    @Test
    public void podMetadataTest() {
        // TODO: test podMetadata
    }

    /**
     * Test the property 'serviceAccountName'
     */
    @Test
    public void serviceAccountNameTest() {
        // TODO: test serviceAccountName
    }

    /**
     * Test the property 'strategy'
     */
    @Test
    public void strategyTest() {
        // TODO: test strategy
    }

}
