/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for AWSCredentials
 */
public class AWSCredentialsTest {
    private final AWSCredentials model = new AWSCredentials();

    /**
     * Model tests for AWSCredentials
     */
    @Test
    public void testAWSCredentials() {
        // TODO: test AWSCredentials
    }

    /**
     * Test the property 'accessKeyId'
     */
    @Test
    public void accessKeyIdTest() {
        // TODO: test accessKeyId
    }

    /**
     * Test the property 'secretAccessKey'
     */
    @Test
    public void secretAccessKeyTest() {
        // TODO: test secretAccessKey
    }

    /**
     * Test the property 'sessionToken'
     */
    @Test
    public void sessionTokenTest() {
        // TODO: test sessionToken
    }

}
