/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for Backoff
 */
public class BackoffTest {
    private final Backoff model = new Backoff();

    /**
     * Model tests for Backoff
     */
    @Test
    public void testBackoff() {
        // TODO: test Backoff
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'factor'
     */
    @Test
    public void factorTest() {
        // TODO: test factor
    }

    /**
     * Test the property 'maxDuration'
     */
    @Test
    public void maxDurationTest() {
        // TODO: test maxDuration
    }

}
