/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for BitbucketServerRepository
 */
public class BitbucketServerRepositoryTest {
    private final BitbucketServerRepository model = new BitbucketServerRepository();

    /**
     * Model tests for BitbucketServerRepository
     */
    @Test
    public void testBitbucketServerRepository() {
        // TODO: test BitbucketServerRepository
    }

    /**
     * Test the property 'projectKey'
     */
    @Test
    public void projectKeyTest() {
        // TODO: test projectKey
    }

    /**
     * Test the property 'repositorySlug'
     */
    @Test
    public void repositorySlugTest() {
        // TODO: test repositorySlug
    }

}
