/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for Capabilities
 */
public class CapabilitiesTest {
    private final Capabilities model = new Capabilities();

    /**
     * Model tests for Capabilities
     */
    @Test
    public void testCapabilities() {
        // TODO: test Capabilities
    }

    /**
     * Test the property 'add'
     */
    @Test
    public void addTest() {
        // TODO: test add
    }

    /**
     * Test the property 'drop'
     */
    @Test
    public void dropTest() {
        // TODO: test drop
    }

}
