/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for ConfigMapPersistence
 */
public class ConfigMapPersistenceTest {
    private final ConfigMapPersistence model = new ConfigMapPersistence();

    /**
     * Model tests for ConfigMapPersistence
     */
    @Test
    public void testConfigMapPersistence() {
        // TODO: test ConfigMapPersistence
    }

    /**
     * Test the property 'createIfNotExist'
     */
    @Test
    public void createIfNotExistTest() {
        // TODO: test createIfNotExist
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
