/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for CreateOptions
 */
public class CreateOptionsTest {
    private final CreateOptions model = new CreateOptions();

    /**
     * Model tests for CreateOptions
     */
    @Test
    public void testCreateOptions() {
        // TODO: test CreateOptions
    }

    /**
     * Test the property 'dryRun'
     */
    @Test
    public void dryRunTest() {
        // TODO: test dryRun
    }

    /**
     * Test the property 'fieldManager'
     */
    @Test
    public void fieldManagerTest() {
        // TODO: test fieldManager
    }

    /**
     * Test the property 'fieldValidation'
     */
    @Test
    public void fieldValidationTest() {
        // TODO: test fieldValidation
    }

}
