/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha.WorkflowSpec;
import io.kubernetes.client.models.V1ObjectMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CronWorkflowSpec
 */
public class CronWorkflowSpecTest {
    private final CronWorkflowSpec model = new CronWorkflowSpec();

    /**
     * Model tests for CronWorkflowSpec
     */
    @Test
    public void testCronWorkflowSpec() {
        // TODO: test CronWorkflowSpec
    }

    /**
     * Test the property 'concurrencyPolicy'
     */
    @Test
    public void concurrencyPolicyTest() {
        // TODO: test concurrencyPolicy
    }

    /**
     * Test the property 'failedJobsHistoryLimit'
     */
    @Test
    public void failedJobsHistoryLimitTest() {
        // TODO: test failedJobsHistoryLimit
    }

    /**
     * Test the property 'schedule'
     */
    @Test
    public void scheduleTest() {
        // TODO: test schedule
    }

    /**
     * Test the property 'startingDeadlineSeconds'
     */
    @Test
    public void startingDeadlineSecondsTest() {
        // TODO: test startingDeadlineSeconds
    }

    /**
     * Test the property 'successfulJobsHistoryLimit'
     */
    @Test
    public void successfulJobsHistoryLimitTest() {
        // TODO: test successfulJobsHistoryLimit
    }

    /**
     * Test the property 'suspend'
     */
    @Test
    public void suspendTest() {
        // TODO: test suspend
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'workflowMetadata'
     */
    @Test
    public void workflowMetadataTest() {
        // TODO: test workflowMetadata
    }

    /**
     * Test the property 'workflowSpec'
     */
    @Test
    public void workflowSpecTest() {
        // TODO: test workflowSpec
    }

}
