/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for CronWorkflowSuspendRequest
 */
public class CronWorkflowSuspendRequestTest {
    private final CronWorkflowSuspendRequest model = new CronWorkflowSuspendRequest();

    /**
     * Model tests for CronWorkflowSuspendRequest
     */
    @Test
    public void testCronWorkflowSuspendRequest() {
        // TODO: test CronWorkflowSuspendRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

}
