/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for DAGTemplate
 */
public class DAGTemplateTest {
    private final DAGTemplate model = new DAGTemplate();

    /**
     * Model tests for DAGTemplate
     */
    @Test
    public void testDAGTemplate() {
        // TODO: test DAGTemplate
    }

    /**
     * Test the property 'failFast'
     */
    @Test
    public void failFastTest() {
        // TODO: test failFast
    }

    /**
     * Test the property 'target'
     */
    @Test
    public void targetTest() {
        // TODO: test target
    }

    /**
     * Test the property 'tasks'
     */
    @Test
    public void tasksTest() {
        // TODO: test tasks
    }

}
