/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for DBSource
 */
public class DBSourceTest {
    private final DBSource model = new DBSource();

    /**
     * Model tests for DBSource
     */
    @Test
    public void testDBSource() {
        // TODO: test DBSource
    }

    /**
     * Test the property 'commitInterval'
     */
    @Test
    public void commitIntervalTest() {
        // TODO: test commitInterval
    }

    /**
     * Test the property 'database'
     */
    @Test
    public void databaseTest() {
        // TODO: test database
    }

    /**
     * Test the property 'initSchema'
     */
    @Test
    public void initSchemaTest() {
        // TODO: test initSchema
    }

    /**
     * Test the property 'offsetColumn'
     */
    @Test
    public void offsetColumnTest() {
        // TODO: test offsetColumn
    }

    /**
     * Test the property 'pollInterval'
     */
    @Test
    public void pollIntervalTest() {
        // TODO: test pollInterval
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

}
