/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for DownwardAPIProjection
 */
public class DownwardAPIProjectionTest {
    private final DownwardAPIProjection model = new DownwardAPIProjection();

    /**
     * Model tests for DownwardAPIProjection
     */
    @Test
    public void testDownwardAPIProjection() {
        // TODO: test DownwardAPIProjection
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

}
