/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for EventSeries
 */
public class EventSeriesTest {
    private final EventSeries model = new EventSeries();

    /**
     * Model tests for EventSeries
     */
    @Test
    public void testEventSeries() {
        // TODO: test EventSeries
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'lastObservedTime'
     */
    @Test
    public void lastObservedTimeTest() {
        // TODO: test lastObservedTime
    }

}
