/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for EventDependency
 */
public class EventDependencyTest {
    private final EventDependency model = new EventDependency();

    /**
     * Model tests for EventDependency
     */
    @Test
    public void testEventDependency() {
        // TODO: test EventDependency
    }

    /**
     * Test the property 'eventName'
     */
    @Test
    public void eventNameTest() {
        // TODO: test eventName
    }

    /**
     * Test the property 'eventSourceName'
     */
    @Test
    public void eventSourceNameTest() {
        // TODO: test eventSourceName
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'filtersLogicalOperator'
     */
    @Test
    public void filtersLogicalOperatorTest() {
        // TODO: test filtersLogicalOperator
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'transform'
     */
    @Test
    public void transformTest() {
        // TODO: test transform
    }

}
