/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for FileEventSource
 */
public class FileEventSourceTest {
    private final FileEventSource model = new FileEventSource();

    /**
     * Model tests for FileEventSource
     */
    @Test
    public void testFileEventSource() {
        // TODO: test FileEventSource
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'polling'
     */
    @Test
    public void pollingTest() {
        // TODO: test polling
    }

    /**
     * Test the property 'watchPathConfig'
     */
    @Test
    public void watchPathConfigTest() {
        // TODO: test watchPathConfig
    }

}
