/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for HTTP
 */
public class HTTPTest {
    private final HTTP model = new HTTP();

    /**
     * Model tests for HTTP
     */
    @Test
    public void testHTTP() {
        // TODO: test HTTP
    }

    /**
     * Test the property 'body'
     */
    @Test
    public void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'bodyFrom'
     */
    @Test
    public void bodyFromTest() {
        // TODO: test bodyFrom
    }

    /**
     * Test the property 'headers'
     */
    @Test
    public void headersTest() {
        // TODO: test headers
    }

    /**
     * Test the property 'insecureSkipVerify'
     */
    @Test
    public void insecureSkipVerifyTest() {
        // TODO: test insecureSkipVerify
    }

    /**
     * Test the property 'method'
     */
    @Test
    public void methodTest() {
        // TODO: test method
    }

    /**
     * Test the property 'successCondition'
     */
    @Test
    public void successConditionTest() {
        // TODO: test successCondition
    }

    /**
     * Test the property 'timeoutSeconds'
     */
    @Test
    public void timeoutSecondsTest() {
        // TODO: test timeoutSeconds
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
