/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for HTTPTrigger
 */
public class HTTPTriggerTest {
    private final HTTPTrigger model = new HTTPTrigger();

    /**
     * Model tests for HTTPTrigger
     */
    @Test
    public void testHTTPTrigger() {
        // TODO: test HTTPTrigger
    }

    /**
     * Test the property 'basicAuth'
     */
    @Test
    public void basicAuthTest() {
        // TODO: test basicAuth
    }

    /**
     * Test the property 'headers'
     */
    @Test
    public void headersTest() {
        // TODO: test headers
    }

    /**
     * Test the property 'method'
     */
    @Test
    public void methodTest() {
        // TODO: test method
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

    /**
     * Test the property 'secureHeaders'
     */
    @Test
    public void secureHeadersTest() {
        // TODO: test secureHeaders
    }

    /**
     * Test the property 'timeout'
     */
    @Test
    public void timeoutTest() {
        // TODO: test timeout
    }

    /**
     * Test the property 'tls'
     */
    @Test
    public void tlsTest() {
        // TODO: test tls
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
