/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for HTTPBodySource
 */
public class HTTPBodySourceTest {
    private final HTTPBodySource model = new HTTPBodySource();

    /**
     * Model tests for HTTPBodySource
     */
    @Test
    public void testHTTPBodySource() {
        // TODO: test HTTPBodySource
    }

    /**
     * Test the property 'bytes'
     */
    @Test
    public void bytesTest() {
        // TODO: test bytes
    }

}
