/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for KafkaSink
 */
public class KafkaSinkTest {
    private final KafkaSink model = new KafkaSink();

    /**
     * Model tests for KafkaSink
     */
    @Test
    public void testKafkaSink() {
        // TODO: test KafkaSink
    }

    /**
     * Test the property 'acks'
     */
    @Test
    public void acksTest() {
        // TODO: test acks
    }

    /**
     * Test the property 'async'
     */
    @Test
    public void asyncTest() {
        // TODO: test async
    }

    /**
     * Test the property 'batchSize'
     */
    @Test
    public void batchSizeTest() {
        // TODO: test batchSize
    }

    /**
     * Test the property 'compressionType'
     */
    @Test
    public void compressionTypeTest() {
        // TODO: test compressionType
    }

    /**
     * Test the property 'enableIdempotence'
     */
    @Test
    public void enableIdempotenceTest() {
        // TODO: test enableIdempotence
    }

    /**
     * Test the property 'kafka'
     */
    @Test
    public void kafkaTest() {
        // TODO: test kafka
    }

    /**
     * Test the property 'linger'
     */
    @Test
    public void lingerTest() {
        // TODO: test linger
    }

    /**
     * Test the property 'maxInflight'
     */
    @Test
    public void maxInflightTest() {
        // TODO: test maxInflight
    }

    /**
     * Test the property 'messageTimeout'
     */
    @Test
    public void messageTimeoutTest() {
        // TODO: test messageTimeout
    }

}
