/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for KafkaConsumerGroup
 */
public class KafkaConsumerGroupTest {
    private final KafkaConsumerGroup model = new KafkaConsumerGroup();

    /**
     * Model tests for KafkaConsumerGroup
     */
    @Test
    public void testKafkaConsumerGroup() {
        // TODO: test KafkaConsumerGroup
    }

    /**
     * Test the property 'groupName'
     */
    @Test
    public void groupNameTest() {
        // TODO: test groupName
    }

    /**
     * Test the property 'oldest'
     */
    @Test
    public void oldestTest() {
        // TODO: test oldest
    }

    /**
     * Test the property 'rebalanceStrategy'
     */
    @Test
    public void rebalanceStrategyTest() {
        // TODO: test rebalanceStrategy
    }

}
