/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for KafkaNET
 */
public class KafkaNETTest {
    private final KafkaNET model = new KafkaNET();

    /**
     * Model tests for KafkaNET
     */
    @Test
    public void testKafkaNET() {
        // TODO: test KafkaNET
    }

    /**
     * Test the property 'sasl'
     */
    @Test
    public void saslTest() {
        // TODO: test sasl
    }

    /**
     * Test the property 'tls'
     */
    @Test
    public void tlsTest() {
        // TODO: test tls
    }

}
