/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha.KafkaNET;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for KafkaConfig
 */
public class KafkaConfigTest {
    private final KafkaConfig model = new KafkaConfig();

    /**
     * Model tests for KafkaConfig
     */
    @Test
    public void testKafkaConfig() {
        // TODO: test KafkaConfig
    }

    /**
     * Test the property 'brokers'
     */
    @Test
    public void brokersTest() {
        // TODO: test brokers
    }

    /**
     * Test the property 'maxMessageBytes'
     */
    @Test
    public void maxMessageBytesTest() {
        // TODO: test maxMessageBytes
    }

    /**
     * Test the property 'net'
     */
    @Test
    public void netTest() {
        // TODO: test net
    }

}
