/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for KafkaEventSource
 */
public class KafkaEventSourceTest {
    private final KafkaEventSource model = new KafkaEventSource();

    /**
     * Model tests for KafkaEventSource
     */
    @Test
    public void testKafkaEventSource() {
        // TODO: test KafkaEventSource
    }

    /**
     * Test the property 'config'
     */
    @Test
    public void configTest() {
        // TODO: test config
    }

    /**
     * Test the property 'connectionBackoff'
     */
    @Test
    public void connectionBackoffTest() {
        // TODO: test connectionBackoff
    }

    /**
     * Test the property 'consumerGroup'
     */
    @Test
    public void consumerGroupTest() {
        // TODO: test consumerGroup
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'jsonBody'
     */
    @Test
    public void jsonBodyTest() {
        // TODO: test jsonBody
    }

    /**
     * Test the property 'limitEventsPerSecond'
     */
    @Test
    public void limitEventsPerSecondTest() {
        // TODO: test limitEventsPerSecond
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'partition'
     */
    @Test
    public void partitionTest() {
        // TODO: test partition
    }

    /**
     * Test the property 'sasl'
     */
    @Test
    public void saslTest() {
        // TODO: test sasl
    }

    /**
     * Test the property 'tls'
     */
    @Test
    public void tlsTest() {
        // TODO: test tls
    }

    /**
     * Test the property 'topic'
     */
    @Test
    public void topicTest() {
        // TODO: test topic
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

}
