/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for LifecycleHandler
 */
public class LifecycleHandlerTest {
    private final LifecycleHandler model = new LifecycleHandler();

    /**
     * Model tests for LifecycleHandler
     */
    @Test
    public void testLifecycleHandler() {
        // TODO: test LifecycleHandler
    }

    /**
     * Test the property 'exec'
     */
    @Test
    public void execTest() {
        // TODO: test exec
    }

    /**
     * Test the property 'httpGet'
     */
    @Test
    public void httpGetTest() {
        // TODO: test httpGet
    }

    /**
     * Test the property 'tcpSocket'
     */
    @Test
    public void tcpSocketTest() {
        // TODO: test tcpSocket
    }

}
