/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for Log
 */
public class LogTest {
    private final Log model = new Log();

    /**
     * Model tests for Log
     */
    @Test
    public void testLog() {
        // TODO: test Log
    }

    /**
     * Test the property 'truncate'
     */
    @Test
    public void truncateTest() {
        // TODO: test truncate
    }

}
