/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for NodeSelectorTerm
 */
public class NodeSelectorTermTest {
    private final NodeSelectorTerm model = new NodeSelectorTerm();

    /**
     * Model tests for NodeSelectorTerm
     */
    @Test
    public void testNodeSelectorTerm() {
        // TODO: test NodeSelectorTerm
    }

    /**
     * Test the property 'matchExpressions'
     */
    @Test
    public void matchExpressionsTest() {
        // TODO: test matchExpressions
    }

    /**
     * Test the property 'matchFields'
     */
    @Test
    public void matchFieldsTest() {
        // TODO: test matchFields
    }

}
