/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for ObjectFieldSelector
 */
public class ObjectFieldSelectorTest {
    private final ObjectFieldSelector model = new ObjectFieldSelector();

    /**
     * Model tests for ObjectFieldSelector
     */
    @Test
    public void testObjectFieldSelector() {
        // TODO: test ObjectFieldSelector
    }

    /**
     * Test the property 'apiVersion'
     */
    @Test
    public void apiVersionTest() {
        // TODO: test apiVersion
    }

    /**
     * Test the property 'fieldPath'
     */
    @Test
    public void fieldPathTest() {
        // TODO: test fieldPath
    }

}
