/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for OpenWhiskTrigger
 */
public class OpenWhiskTriggerTest {
    private final OpenWhiskTrigger model = new OpenWhiskTrigger();

    /**
     * Model tests for OpenWhiskTrigger
     */
    @Test
    public void testOpenWhiskTrigger() {
        // TODO: test OpenWhiskTrigger
    }

    /**
     * Test the property 'actionName'
     */
    @Test
    public void actionNameTest() {
        // TODO: test actionName
    }

    /**
     * Test the property 'authToken'
     */
    @Test
    public void authTokenTest() {
        // TODO: test authToken
    }

    /**
     * Test the property 'host'
     */
    @Test
    public void hostTest() {
        // TODO: test host
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

}
