/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for OSSArtifact
 */
public class OSSArtifactTest {
    private final OSSArtifact model = new OSSArtifact();

    /**
     * Model tests for OSSArtifact
     */
    @Test
    public void testOSSArtifact() {
        // TODO: test OSSArtifact
    }

    /**
     * Test the property 'accessKeySecret'
     */
    @Test
    public void accessKeySecretTest() {
        // TODO: test accessKeySecret
    }

    /**
     * Test the property 'bucket'
     */
    @Test
    public void bucketTest() {
        // TODO: test bucket
    }

    /**
     * Test the property 'createBucketIfNotPresent'
     */
    @Test
    public void createBucketIfNotPresentTest() {
        // TODO: test createBucketIfNotPresent
    }

    /**
     * Test the property 'endpoint'
     */
    @Test
    public void endpointTest() {
        // TODO: test endpoint
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'lifecycleRule'
     */
    @Test
    public void lifecycleRuleTest() {
        // TODO: test lifecycleRule
    }

    /**
     * Test the property 'secretKeySecret'
     */
    @Test
    public void secretKeySecretTest() {
        // TODO: test secretKeySecret
    }

    /**
     * Test the property 'securityToken'
     */
    @Test
    public void securityTokenTest() {
        // TODO: test securityToken
    }

}
