/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for PodAffinityTerm
 */
public class PodAffinityTermTest {
    private final PodAffinityTerm model = new PodAffinityTerm();

    /**
     * Model tests for PodAffinityTerm
     */
    @Test
    public void testPodAffinityTerm() {
        // TODO: test PodAffinityTerm
    }

    /**
     * Test the property 'labelSelector'
     */
    @Test
    public void labelSelectorTest() {
        // TODO: test labelSelector
    }

    /**
     * Test the property 'namespaceSelector'
     */
    @Test
    public void namespaceSelectorTest() {
        // TODO: test namespaceSelector
    }

    /**
     * Test the property 'namespaces'
     */
    @Test
    public void namespacesTest() {
        // TODO: test namespaces
    }

    /**
     * Test the property 'topologyKey'
     */
    @Test
    public void topologyKeyTest() {
        // TODO: test topologyKey
    }

}
