/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for PulsarTrigger
 */
public class PulsarTriggerTest {
    private final PulsarTrigger model = new PulsarTrigger();

    /**
     * Model tests for PulsarTrigger
     */
    @Test
    public void testPulsarTrigger() {
        // TODO: test PulsarTrigger
    }

    /**
     * Test the property 'authTokenSecret'
     */
    @Test
    public void authTokenSecretTest() {
        // TODO: test authTokenSecret
    }

    /**
     * Test the property 'connectionBackoff'
     */
    @Test
    public void connectionBackoffTest() {
        // TODO: test connectionBackoff
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

    /**
     * Test the property 'tls'
     */
    @Test
    public void tlsTest() {
        // TODO: test tls
    }

    /**
     * Test the property 'tlsAllowInsecureConnection'
     */
    @Test
    public void tlsAllowInsecureConnectionTest() {
        // TODO: test tlsAllowInsecureConnection
    }

    /**
     * Test the property 'tlsTrustCertsSecret'
     */
    @Test
    public void tlsTrustCertsSecretTest() {
        // TODO: test tlsTrustCertsSecret
    }

    /**
     * Test the property 'tlsValidateHostname'
     */
    @Test
    public void tlsValidateHostnameTest() {
        // TODO: test tlsValidateHostname
    }

    /**
     * Test the property 'topic'
     */
    @Test
    public void topicTest() {
        // TODO: test topic
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
