/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for ResubmitArchivedWorkflowRequest
 */
public class ResubmitArchivedWorkflowRequestTest {
    private final ResubmitArchivedWorkflowRequest model = new ResubmitArchivedWorkflowRequest();

    /**
     * Model tests for ResubmitArchivedWorkflowRequest
     */
    @Test
    public void testResubmitArchivedWorkflowRequest() {
        // TODO: test ResubmitArchivedWorkflowRequest
    }

    /**
     * Test the property 'memoized'
     */
    @Test
    public void memoizedTest() {
        // TODO: test memoized
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'uid'
     */
    @Test
    public void uidTest() {
        // TODO: test uid
    }

}
