/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for SemaphoreRef
 */
public class SemaphoreRefTest {
    private final SemaphoreRef model = new SemaphoreRef();

    /**
     * Model tests for SemaphoreRef
     */
    @Test
    public void testSemaphoreRef() {
        // TODO: test SemaphoreRef
    }

    /**
     * Test the property 'configMapKeyRef'
     */
    @Test
    public void configMapKeyRefTest() {
        // TODO: test configMapKeyRef
    }

}
