/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for SensorSpec
 */
public class SensorSpecTest {
    private final SensorSpec model = new SensorSpec();

    /**
     * Model tests for SensorSpec
     */
    @Test
    public void testSensorSpec() {
        // TODO: test SensorSpec
    }

    /**
     * Test the property 'dependencies'
     */
    @Test
    public void dependenciesTest() {
        // TODO: test dependencies
    }

    /**
     * Test the property 'errorOnFailedRound'
     */
    @Test
    public void errorOnFailedRoundTest() {
        // TODO: test errorOnFailedRound
    }

    /**
     * Test the property 'eventBusName'
     */
    @Test
    public void eventBusNameTest() {
        // TODO: test eventBusName
    }

    /**
     * Test the property 'replicas'
     */
    @Test
    public void replicasTest() {
        // TODO: test replicas
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'triggers'
     */
    @Test
    public void triggersTest() {
        // TODO: test triggers
    }

}
