/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for Service
 */
public class ServiceTest {
    private final Service model = new Service();

    /**
     * Model tests for Service
     */
    @Test
    public void testService() {
        // TODO: test Service
    }

    /**
     * Test the property 'clusterIP'
     */
    @Test
    public void clusterIPTest() {
        // TODO: test clusterIP
    }

    /**
     * Test the property 'ports'
     */
    @Test
    public void portsTest() {
        // TODO: test ports
    }

}
