/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for SQLStatement
 */
public class SQLStatementTest {
    private final SQLStatement model = new SQLStatement();

    /**
     * Model tests for SQLStatement
     */
    @Test
    public void testSQLStatement() {
        // TODO: test SQLStatement
    }

    /**
     * Test the property 'args'
     */
    @Test
    public void argsTest() {
        // TODO: test args
    }

    /**
     * Test the property 'sql'
     */
    @Test
    public void sqlTest() {
        // TODO: test sql
    }

}
