/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for StreamError
 */
public class StreamErrorTest {
    private final StreamError model = new StreamError();

    /**
     * Model tests for StreamError
     */
    @Test
    public void testStreamError() {
        // TODO: test StreamError
    }

    /**
     * Test the property 'details'
     */
    @Test
    public void detailsTest() {
        // TODO: test details
    }

    /**
     * Test the property 'grpcCode'
     */
    @Test
    public void grpcCodeTest() {
        // TODO: test grpcCode
    }

    /**
     * Test the property 'httpCode'
     */
    @Test
    public void httpCodeTest() {
        // TODO: test httpCode
    }

    /**
     * Test the property 'httpStatus'
     */
    @Test
    public void httpStatusTest() {
        // TODO: test httpStatus
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
