/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for StripeEventSource
 */
public class StripeEventSourceTest {
    private final StripeEventSource model = new StripeEventSource();

    /**
     * Model tests for StripeEventSource
     */
    @Test
    public void testStripeEventSource() {
        // TODO: test StripeEventSource
    }

    /**
     * Test the property 'apiKey'
     */
    @Test
    public void apiKeyTest() {
        // TODO: test apiKey
    }

    /**
     * Test the property 'createWebhook'
     */
    @Test
    public void createWebhookTest() {
        // TODO: test createWebhook
    }

    /**
     * Test the property 'eventFilter'
     */
    @Test
    public void eventFilterTest() {
        // TODO: test eventFilter
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'webhook'
     */
    @Test
    public void webhookTest() {
        // TODO: test webhook
    }

}
