/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for SubmitOpts
 */
public class SubmitOptsTest {
    private final SubmitOpts model = new SubmitOpts();

    /**
     * Model tests for SubmitOpts
     */
    @Test
    public void testSubmitOpts() {
        // TODO: test SubmitOpts
    }

    /**
     * Test the property 'annotations'
     */
    @Test
    public void annotationsTest() {
        // TODO: test annotations
    }

    /**
     * Test the property 'dryRun'
     */
    @Test
    public void dryRunTest() {
        // TODO: test dryRun
    }

    /**
     * Test the property 'entryPoint'
     */
    @Test
    public void entryPointTest() {
        // TODO: test entryPoint
    }

    /**
     * Test the property 'generateName'
     */
    @Test
    public void generateNameTest() {
        // TODO: test generateName
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ownerReference'
     */
    @Test
    public void ownerReferenceTest() {
        // TODO: test ownerReference
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'podPriorityClassName'
     */
    @Test
    public void podPriorityClassNameTest() {
        // TODO: test podPriorityClassName
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'serverDryRun'
     */
    @Test
    public void serverDryRunTest() {
        // TODO: test serverDryRun
    }

    /**
     * Test the property 'serviceAccount'
     */
    @Test
    public void serviceAccountTest() {
        // TODO: test serviceAccount
    }

}
