/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TLSConfig
 */
public class TLSConfigTest {
    private final TLSConfig model = new TLSConfig();

    /**
     * Model tests for TLSConfig
     */
    @Test
    public void testTLSConfig() {
        // TODO: test TLSConfig
    }

    /**
     * Test the property 'caCertSecret'
     */
    @Test
    public void caCertSecretTest() {
        // TODO: test caCertSecret
    }

    /**
     * Test the property 'clientCertSecret'
     */
    @Test
    public void clientCertSecretTest() {
        // TODO: test clientCertSecret
    }

    /**
     * Test the property 'clientKeySecret'
     */
    @Test
    public void clientKeySecretTest() {
        // TODO: test clientKeySecret
    }

    /**
     * Test the property 'insecureSkipVerify'
     */
    @Test
    public void insecureSkipVerifyTest() {
        // TODO: test insecureSkipVerify
    }

}
