/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for TLS
 */
public class TLSTest {
    private final TLS model = new TLS();

    /**
     * Model tests for TLS
     */
    @Test
    public void testTLS() {
        // TODO: test TLS
    }

    /**
     * Test the property 'caCertSecret'
     */
    @Test
    public void caCertSecretTest() {
        // TODO: test caCertSecret
    }

    /**
     * Test the property 'certSecret'
     */
    @Test
    public void certSecretTest() {
        // TODO: test certSecret
    }

    /**
     * Test the property 'keySecret'
     */
    @Test
    public void keySecretTest() {
        // TODO: test keySecret
    }

}
