/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for TriggerParameter
 */
public class TriggerParameterTest {
    private final TriggerParameter model = new TriggerParameter();

    /**
     * Model tests for TriggerParameter
     */
    @Test
    public void testTriggerParameter() {
        // TODO: test TriggerParameter
    }

    /**
     * Test the property 'dest'
     */
    @Test
    public void destTest() {
        // TODO: test dest
    }

    /**
     * Test the property 'operation'
     */
    @Test
    public void operationTest() {
        // TODO: test operation
    }

    /**
     * Test the property 'src'
     */
    @Test
    public void srcTest() {
        // TODO: test src
    }

}
