/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for TTLStrategy
 */
public class TTLStrategyTest {
    private final TTLStrategy model = new TTLStrategy();

    /**
     * Model tests for TTLStrategy
     */
    @Test
    public void testTTLStrategy() {
        // TODO: test TTLStrategy
    }

    /**
     * Test the property 'secondsAfterCompletion'
     */
    @Test
    public void secondsAfterCompletionTest() {
        // TODO: test secondsAfterCompletion
    }

    /**
     * Test the property 'secondsAfterFailure'
     */
    @Test
    public void secondsAfterFailureTest() {
        // TODO: test secondsAfterFailure
    }

    /**
     * Test the property 'secondsAfterSuccess'
     */
    @Test
    public void secondsAfterSuccessTest() {
        // TODO: test secondsAfterSuccess
    }

}
