/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for V1EnvVar
 */
public class V1EnvVarTest {
    private final V1EnvVar model = new V1EnvVar();

    /**
     * Model tests for V1EnvVar
     */
    @Test
    public void testV1EnvVar() {
        // TODO: test V1EnvVar
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'valueFrom'
     */
    @Test
    public void valueFromTest() {
        // TODO: test valueFrom
    }

}
