/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha.SELinuxOptions;
import io.argoproj.workflow.v1alpha.SeccompProfile;
import io.argoproj.workflow.v1alpha.Sysctl;
import io.argoproj.workflow.v1alpha.WindowsSecurityContextOptions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V1PodSecurityContext
 */
public class V1PodSecurityContextTest {
    private final V1PodSecurityContext model = new V1PodSecurityContext();

    /**
     * Model tests for V1PodSecurityContext
     */
    @Test
    public void testV1PodSecurityContext() {
        // TODO: test V1PodSecurityContext
    }

    /**
     * Test the property 'fsGroup'
     */
    @Test
    public void fsGroupTest() {
        // TODO: test fsGroup
    }

    /**
     * Test the property 'fsGroupChangePolicy'
     */
    @Test
    public void fsGroupChangePolicyTest() {
        // TODO: test fsGroupChangePolicy
    }

    /**
     * Test the property 'runAsGroup'
     */
    @Test
    public void runAsGroupTest() {
        // TODO: test runAsGroup
    }

    /**
     * Test the property 'runAsNonRoot'
     */
    @Test
    public void runAsNonRootTest() {
        // TODO: test runAsNonRoot
    }

    /**
     * Test the property 'runAsUser'
     */
    @Test
    public void runAsUserTest() {
        // TODO: test runAsUser
    }

    /**
     * Test the property 'seLinuxOptions'
     */
    @Test
    public void seLinuxOptionsTest() {
        // TODO: test seLinuxOptions
    }

    /**
     * Test the property 'seccompProfile'
     */
    @Test
    public void seccompProfileTest() {
        // TODO: test seccompProfile
    }

    /**
     * Test the property 'supplementalGroups'
     */
    @Test
    public void supplementalGroupsTest() {
        // TODO: test supplementalGroups
    }

    /**
     * Test the property 'sysctls'
     */
    @Test
    public void sysctlsTest() {
        // TODO: test sysctls
    }

    /**
     * Test the property 'windowsOptions'
     */
    @Test
    public void windowsOptionsTest() {
        // TODO: test windowsOptions
    }

}
