/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for V1PodDNSConfig
 */
public class V1PodDNSConfigTest {
    private final V1PodDNSConfig model = new V1PodDNSConfig();

    /**
     * Model tests for V1PodDNSConfig
     */
    @Test
    public void testV1PodDNSConfig() {
        // TODO: test V1PodDNSConfig
    }

    /**
     * Test the property 'nameservers'
     */
    @Test
    public void nameserversTest() {
        // TODO: test nameservers
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'searches'
     */
    @Test
    public void searchesTest() {
        // TODO: test searches
    }

}
