/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for V1VolumeDevice
 */
public class V1VolumeDeviceTest {
    private final V1VolumeDevice model = new V1VolumeDevice();

    /**
     * Model tests for V1VolumeDevice
     */
    @Test
    public void testV1VolumeDevice() {
        // TODO: test V1VolumeDevice
    }

    /**
     * Test the property 'devicePath'
     */
    @Test
    public void devicePathTest() {
        // TODO: test devicePath
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
