/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for V1VolumeMount
 */
public class V1VolumeMountTest {
    private final V1VolumeMount model = new V1VolumeMount();

    /**
     * Model tests for V1VolumeMount
     */
    @Test
    public void testV1VolumeMount() {
        // TODO: test V1VolumeMount
    }

    /**
     * Test the property 'mountPath'
     */
    @Test
    public void mountPathTest() {
        // TODO: test mountPath
    }

    /**
     * Test the property 'mountPropagation'
     */
    @Test
    public void mountPropagationTest() {
        // TODO: test mountPropagation
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'readOnly'
     */
    @Test
    public void readOnlyTest() {
        // TODO: test readOnly
    }

    /**
     * Test the property 'subPath'
     */
    @Test
    public void subPathTest() {
        // TODO: test subPath
    }

    /**
     * Test the property 'subPathExpr'
     */
    @Test
    public void subPathExprTest() {
        // TODO: test subPathExpr
    }

}
