/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for VolumeSource
 */
public class VolumeSourceTest {
    private final VolumeSource model = new VolumeSource();

    /**
     * Model tests for VolumeSource
     */
    @Test
    public void testVolumeSource() {
        // TODO: test VolumeSource
    }

    /**
     * Test the property 'abstractVolumeSource'
     */
    @Test
    public void abstractVolumeSourceTest() {
        // TODO: test abstractVolumeSource
    }

    /**
     * Test the property 'concurrency'
     */
    @Test
    public void concurrencyTest() {
        // TODO: test concurrency
    }

    /**
     * Test the property 'pollPeriod'
     */
    @Test
    public void pollPeriodTest() {
        // TODO: test pollPeriod
    }

    /**
     * Test the property 'readOnly'
     */
    @Test
    public void readOnlyTest() {
        // TODO: test readOnly
    }

}
