/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for VsphereVirtualDiskVolumeSource
 */
public class VsphereVirtualDiskVolumeSourceTest {
    private final VsphereVirtualDiskVolumeSource model = new VsphereVirtualDiskVolumeSource();

    /**
     * Model tests for VsphereVirtualDiskVolumeSource
     */
    @Test
    public void testVsphereVirtualDiskVolumeSource() {
        // TODO: test VsphereVirtualDiskVolumeSource
    }

    /**
     * Test the property 'fsType'
     */
    @Test
    public void fsTypeTest() {
        // TODO: test fsType
    }

    /**
     * Test the property 'storagePolicyID'
     */
    @Test
    public void storagePolicyIDTest() {
        // TODO: test storagePolicyID
    }

    /**
     * Test the property 'storagePolicyName'
     */
    @Test
    public void storagePolicyNameTest() {
        // TODO: test storagePolicyName
    }

    /**
     * Test the property 'volumePath'
     */
    @Test
    public void volumePathTest() {
        // TODO: test volumePath
    }

}
