/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for WatchPathConfig
 */
public class WatchPathConfigTest {
    private final WatchPathConfig model = new WatchPathConfig();

    /**
     * Model tests for WatchPathConfig
     */
    @Test
    public void testWatchPathConfig() {
        // TODO: test WatchPathConfig
    }

    /**
     * Test the property 'directory'
     */
    @Test
    public void directoryTest() {
        // TODO: test directory
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'pathRegexp'
     */
    @Test
    public void pathRegexpTest() {
        // TODO: test pathRegexp
    }

}
