/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for WeightedPodAffinityTerm
 */
public class WeightedPodAffinityTermTest {
    private final WeightedPodAffinityTerm model = new WeightedPodAffinityTerm();

    /**
     * Model tests for WeightedPodAffinityTerm
     */
    @Test
    public void testWeightedPodAffinityTerm() {
        // TODO: test WeightedPodAffinityTerm
    }

    /**
     * Test the property 'podAffinityTerm'
     */
    @Test
    public void podAffinityTermTest() {
        // TODO: test podAffinityTerm
    }

    /**
     * Test the property 'weight'
     */
    @Test
    public void weightTest() {
        // TODO: test weight
    }

}
