/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for WorkflowRetryRequest
 */
public class WorkflowRetryRequestTest {
    private final WorkflowRetryRequest model = new WorkflowRetryRequest();

    /**
     * Model tests for WorkflowRetryRequest
     */
    @Test
    public void testWorkflowRetryRequest() {
        // TODO: test WorkflowRetryRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'nodeFieldSelector'
     */
    @Test
    public void nodeFieldSelectorTest() {
        // TODO: test nodeFieldSelector
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'restartSuccessful'
     */
    @Test
    public void restartSuccessfulTest() {
        // TODO: test restartSuccessful
    }

}
