/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import org.junit.Test;


/**
 * Model tests for WorkflowCreateRequest
 */
public class WorkflowCreateRequestTest {
    private final WorkflowCreateRequest model = new WorkflowCreateRequest();

    /**
     * Model tests for WorkflowCreateRequest
     */
    @Test
    public void testWorkflowCreateRequest() {
        // TODO: test WorkflowCreateRequest
    }

    /**
     * Test the property 'createOptions'
     */
    @Test
    public void createOptionsTest() {
        // TODO: test createOptions
    }

    /**
     * Test the property 'instanceID'
     */
    @Test
    public void instanceIDTest() {
        // TODO: test instanceID
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'serverDryRun'
     */
    @Test
    public void serverDryRunTest() {
        // TODO: test serverDryRun
    }

    /**
     * Test the property 'workflow'
     */
    @Test
    public void workflowTest() {
        // TODO: test workflow
    }

}
