/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha.CreateOptions;
import io.argoproj.workflow.v1alpha.WorkflowTemplate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WorkflowTemplateCreateRequest
 */
public class WorkflowTemplateCreateRequestTest {
    private final WorkflowTemplateCreateRequest model = new WorkflowTemplateCreateRequest();

    /**
     * Model tests for WorkflowTemplateCreateRequest
     */
    @Test
    public void testWorkflowTemplateCreateRequest() {
        // TODO: test WorkflowTemplateCreateRequest
    }

    /**
     * Test the property 'createOptions'
     */
    @Test
    public void createOptionsTest() {
        // TODO: test createOptions
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

}
