/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha.BitbucketBasicAuth;
import io.kubernetes.client.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BitbucketAuth
 */

public class BitbucketAuth {
  public static final String SERIALIZED_NAME_BASIC = "basic";
  @SerializedName(SERIALIZED_NAME_BASIC)
  private BitbucketBasicAuth basic;

  public static final String SERIALIZED_NAME_OAUTH_TOKEN = "oauthToken";
  @SerializedName(SERIALIZED_NAME_OAUTH_TOKEN)
  private V1SecretKeySelector oauthToken;


  public BitbucketAuth basic(BitbucketBasicAuth basic) {
    
    this.basic = basic;
    return this;
  }

   /**
   * Get basic
   * @return basic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BitbucketBasicAuth getBasic() {
    return basic;
  }


  public void setBasic(BitbucketBasicAuth basic) {
    this.basic = basic;
  }


  public BitbucketAuth oauthToken(V1SecretKeySelector oauthToken) {
    
    this.oauthToken = oauthToken;
    return this;
  }

   /**
   * Get oauthToken
   * @return oauthToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1SecretKeySelector getOauthToken() {
    return oauthToken;
  }


  public void setOauthToken(V1SecretKeySelector oauthToken) {
    this.oauthToken = oauthToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BitbucketAuth ioArgoprojEventsV1alpha1BitbucketAuth = (BitbucketAuth) o;
    return Objects.equals(this.basic, ioArgoprojEventsV1alpha1BitbucketAuth.basic) &&
        Objects.equals(this.oauthToken, ioArgoprojEventsV1alpha1BitbucketAuth.oauthToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(basic, oauthToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BitbucketAuth {\n");
    sb.append("    basic: ").append(toIndentedString(basic)).append("\n");
    sb.append("    oauthToken: ").append(toIndentedString(oauthToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

