/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha.Condition;
import io.kubernetes.client.models.V1ObjectReference;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * CronWorkflowStatus is the status of a CronWorkflow
 */
@ApiModel(description = "CronWorkflowStatus is the status of a CronWorkflow")

public class CronWorkflowStatus {
  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private List<V1ObjectReference> active = new ArrayList<V1ObjectReference>();

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<Condition> conditions = new ArrayList<Condition>();

  public static final String SERIALIZED_NAME_LAST_SCHEDULED_TIME = "lastScheduledTime";
  @SerializedName(SERIALIZED_NAME_LAST_SCHEDULED_TIME)
  private DateTime lastScheduledTime;


  public CronWorkflowStatus active(List<V1ObjectReference> active) {
    
    this.active = active;
    return this;
  }

  public CronWorkflowStatus addActiveItem(V1ObjectReference activeItem) {
    this.active.add(activeItem);
    return this;
  }

   /**
   * Active is a list of active workflows stemming from this CronWorkflow
   * @return active
  **/
  @ApiModelProperty(required = true, value = "Active is a list of active workflows stemming from this CronWorkflow")

  public List<V1ObjectReference> getActive() {
    return active;
  }


  public void setActive(List<V1ObjectReference> active) {
    this.active = active;
  }


  public CronWorkflowStatus conditions(List<Condition> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public CronWorkflowStatus addConditionsItem(Condition conditionsItem) {
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Conditions is a list of conditions the CronWorkflow may have
   * @return conditions
  **/
  @ApiModelProperty(required = true, value = "Conditions is a list of conditions the CronWorkflow may have")

  public List<Condition> getConditions() {
    return conditions;
  }


  public void setConditions(List<Condition> conditions) {
    this.conditions = conditions;
  }


  public CronWorkflowStatus lastScheduledTime(DateTime lastScheduledTime) {
    
    this.lastScheduledTime = lastScheduledTime;
    return this;
  }

   /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @return lastScheduledTime
  **/
  @ApiModelProperty(required = true, value = "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.")

  public DateTime getLastScheduledTime() {
    return lastScheduledTime;
  }


  public void setLastScheduledTime(DateTime lastScheduledTime) {
    this.lastScheduledTime = lastScheduledTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CronWorkflowStatus ioArgoprojWorkflowV1alpha1CronWorkflowStatus = (CronWorkflowStatus) o;
    return Objects.equals(this.active, ioArgoprojWorkflowV1alpha1CronWorkflowStatus.active) &&
        Objects.equals(this.conditions, ioArgoprojWorkflowV1alpha1CronWorkflowStatus.conditions) &&
        Objects.equals(this.lastScheduledTime, ioArgoprojWorkflowV1alpha1CronWorkflowStatus.lastScheduledTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, conditions, lastScheduledTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CronWorkflowStatus {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    lastScheduledTime: ").append(toIndentedString(lastScheduledTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

