/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ExprFilter
 */

public class ExprFilter {
  public static final String SERIALIZED_NAME_EXPR = "expr";
  @SerializedName(SERIALIZED_NAME_EXPR)
  private String expr;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private List<PayloadField> fields = null;


  public ExprFilter expr(String expr) {
    
    this.expr = expr;
    return this;
  }

   /**
   * Expr refers to the expression that determines the outcome of the filter.
   * @return expr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Expr refers to the expression that determines the outcome of the filter.")

  public String getExpr() {
    return expr;
  }


  public void setExpr(String expr) {
    this.expr = expr;
  }


  public ExprFilter fields(List<PayloadField> fields) {
    
    this.fields = fields;
    return this;
  }

  public ExprFilter addFieldsItem(PayloadField fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<PayloadField>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Fields refers to set of keys that refer to the paths within event payload.
   * @return fields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Fields refers to set of keys that refer to the paths within event payload.")

  public List<PayloadField> getFields() {
    return fields;
  }


  public void setFields(List<PayloadField> fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExprFilter ioArgoprojEventsV1alpha1ExprFilter = (ExprFilter) o;
    return Objects.equals(this.expr, ioArgoprojEventsV1alpha1ExprFilter.expr) &&
        Objects.equals(this.fields, ioArgoprojEventsV1alpha1ExprFilter.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expr, fields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExprFilter {\n");
    sb.append("    expr: ").append(toIndentedString(expr)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

