/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha.BasicAuth;
import io.argoproj.workflow.v1alpha.SecureHeader;
import io.argoproj.workflow.v1alpha.TLSConfig;
import io.argoproj.workflow.v1alpha.TriggerParameter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * HTTPTrigger
 */

public class HTTPTrigger {
  public static final String SERIALIZED_NAME_BASIC_AUTH = "basicAuth";
  @SerializedName(SERIALIZED_NAME_BASIC_AUTH)
  private BasicAuth basicAuth;

  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  private Map<String, String> headers = null;

  public static final String SERIALIZED_NAME_METHOD = "method";
  @SerializedName(SERIALIZED_NAME_METHOD)
  private String method;

  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  private List<TriggerParameter> parameters = null;

  public static final String SERIALIZED_NAME_PAYLOAD = "payload";
  @SerializedName(SERIALIZED_NAME_PAYLOAD)
  private List<TriggerParameter> payload = null;

  public static final String SERIALIZED_NAME_SECURE_HEADERS = "secureHeaders";
  @SerializedName(SERIALIZED_NAME_SECURE_HEADERS)
  private List<SecureHeader> secureHeaders = null;

  public static final String SERIALIZED_NAME_TIMEOUT = "timeout";
  @SerializedName(SERIALIZED_NAME_TIMEOUT)
  private String timeout;

  public static final String SERIALIZED_NAME_TLS = "tls";
  @SerializedName(SERIALIZED_NAME_TLS)
  private TLSConfig tls;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;


  public HTTPTrigger basicAuth(BasicAuth basicAuth) {
    
    this.basicAuth = basicAuth;
    return this;
  }

   /**
   * Get basicAuth
   * @return basicAuth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BasicAuth getBasicAuth() {
    return basicAuth;
  }


  public void setBasicAuth(BasicAuth basicAuth) {
    this.basicAuth = basicAuth;
  }


  public HTTPTrigger headers(Map<String, String> headers) {
    
    this.headers = headers;
    return this;
  }

  public HTTPTrigger putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<String, String>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getHeaders() {
    return headers;
  }


  public void setHeaders(Map<String, String> headers) {
    this.headers = headers;
  }


  public HTTPTrigger method(String method) {
    
    this.method = method;
    return this;
  }

   /**
   * Get method
   * @return method
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMethod() {
    return method;
  }


  public void setMethod(String method) {
    this.method = method;
  }


  public HTTPTrigger parameters(List<TriggerParameter> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public HTTPTrigger addParametersItem(TriggerParameter parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<TriggerParameter>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * Parameters is the list of key-value extracted from event&#39;s payload that are applied to the HTTP trigger resource.
   * @return parameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Parameters is the list of key-value extracted from event's payload that are applied to the HTTP trigger resource.")

  public List<TriggerParameter> getParameters() {
    return parameters;
  }


  public void setParameters(List<TriggerParameter> parameters) {
    this.parameters = parameters;
  }


  public HTTPTrigger payload(List<TriggerParameter> payload) {
    
    this.payload = payload;
    return this;
  }

  public HTTPTrigger addPayloadItem(TriggerParameter payloadItem) {
    if (this.payload == null) {
      this.payload = new ArrayList<TriggerParameter>();
    }
    this.payload.add(payloadItem);
    return this;
  }

   /**
   * Get payload
   * @return payload
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<TriggerParameter> getPayload() {
    return payload;
  }


  public void setPayload(List<TriggerParameter> payload) {
    this.payload = payload;
  }


  public HTTPTrigger secureHeaders(List<SecureHeader> secureHeaders) {
    
    this.secureHeaders = secureHeaders;
    return this;
  }

  public HTTPTrigger addSecureHeadersItem(SecureHeader secureHeadersItem) {
    if (this.secureHeaders == null) {
      this.secureHeaders = new ArrayList<SecureHeader>();
    }
    this.secureHeaders.add(secureHeadersItem);
    return this;
  }

   /**
   * Get secureHeaders
   * @return secureHeaders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<SecureHeader> getSecureHeaders() {
    return secureHeaders;
  }


  public void setSecureHeaders(List<SecureHeader> secureHeaders) {
    this.secureHeaders = secureHeaders;
  }


  public HTTPTrigger timeout(String timeout) {
    
    this.timeout = timeout;
    return this;
  }

   /**
   * Get timeout
   * @return timeout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTimeout() {
    return timeout;
  }


  public void setTimeout(String timeout) {
    this.timeout = timeout;
  }


  public HTTPTrigger tls(TLSConfig tls) {
    
    this.tls = tls;
    return this;
  }

   /**
   * Get tls
   * @return tls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TLSConfig getTls() {
    return tls;
  }


  public void setTls(TLSConfig tls) {
    this.tls = tls;
  }


  public HTTPTrigger url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * URL refers to the URL to send HTTP request to.
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URL refers to the URL to send HTTP request to.")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HTTPTrigger ioArgoprojEventsV1alpha1HTTPTrigger = (HTTPTrigger) o;
    return Objects.equals(this.basicAuth, ioArgoprojEventsV1alpha1HTTPTrigger.basicAuth) &&
        Objects.equals(this.headers, ioArgoprojEventsV1alpha1HTTPTrigger.headers) &&
        Objects.equals(this.method, ioArgoprojEventsV1alpha1HTTPTrigger.method) &&
        Objects.equals(this.parameters, ioArgoprojEventsV1alpha1HTTPTrigger.parameters) &&
        Objects.equals(this.payload, ioArgoprojEventsV1alpha1HTTPTrigger.payload) &&
        Objects.equals(this.secureHeaders, ioArgoprojEventsV1alpha1HTTPTrigger.secureHeaders) &&
        Objects.equals(this.timeout, ioArgoprojEventsV1alpha1HTTPTrigger.timeout) &&
        Objects.equals(this.tls, ioArgoprojEventsV1alpha1HTTPTrigger.tls) &&
        Objects.equals(this.url, ioArgoprojEventsV1alpha1HTTPTrigger.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(basicAuth, headers, method, parameters, payload, secureHeaders, timeout, tls, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HTTPTrigger {\n");
    sb.append("    basicAuth: ").append(toIndentedString(basicAuth)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    secureHeaders: ").append(toIndentedString(secureHeaders)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    tls: ").append(toIndentedString(tls)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

