/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha.JetStream;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * JetStreamSink
 */

public class JetStreamSink {
  public static final String SERIALIZED_NAME_JETSTREAM = "jetstream";
  @SerializedName(SERIALIZED_NAME_JETSTREAM)
  private JetStream jetstream;


  public JetStreamSink jetstream(JetStream jetstream) {
    
    this.jetstream = jetstream;
    return this;
  }

   /**
   * Get jetstream
   * @return jetstream
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JetStream getJetstream() {
    return jetstream;
  }


  public void setJetstream(JetStream jetstream) {
    this.jetstream = jetstream;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JetStreamSink githubComArgoprojLabsArgoDataflowApiV1alpha1JetStreamSink = (JetStreamSink) o;
    return Objects.equals(this.jetstream, githubComArgoprojLabsArgoDataflowApiV1alpha1JetStreamSink.jetstream);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jetstream);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JetStreamSink {\n");
    sb.append("    jetstream: ").append(toIndentedString(jetstream)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

