/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SemaphoreHolding
 */

public class SemaphoreHolding {
  public static final String SERIALIZED_NAME_HOLDERS = "holders";
  @SerializedName(SERIALIZED_NAME_HOLDERS)
  private List<String> holders = null;

  public static final String SERIALIZED_NAME_SEMAPHORE = "semaphore";
  @SerializedName(SERIALIZED_NAME_SEMAPHORE)
  private String semaphore;


  public SemaphoreHolding holders(List<String> holders) {
    
    this.holders = holders;
    return this;
  }

  public SemaphoreHolding addHoldersItem(String holdersItem) {
    if (this.holders == null) {
      this.holders = new ArrayList<String>();
    }
    this.holders.add(holdersItem);
    return this;
  }

   /**
   * Holders stores the list of current holder names in the io.argoproj.workflow.v1alpha1.
   * @return holders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Holders stores the list of current holder names in the io.argoproj.workflow.v1alpha1.")

  public List<String> getHolders() {
    return holders;
  }


  public void setHolders(List<String> holders) {
    this.holders = holders;
  }


  public SemaphoreHolding semaphore(String semaphore) {
    
    this.semaphore = semaphore;
    return this;
  }

   /**
   * Semaphore stores the semaphore name.
   * @return semaphore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Semaphore stores the semaphore name.")

  public String getSemaphore() {
    return semaphore;
  }


  public void setSemaphore(String semaphore) {
    this.semaphore = semaphore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SemaphoreHolding ioArgoprojWorkflowV1alpha1SemaphoreHolding = (SemaphoreHolding) o;
    return Objects.equals(this.holders, ioArgoprojWorkflowV1alpha1SemaphoreHolding.holders) &&
        Objects.equals(this.semaphore, ioArgoprojWorkflowV1alpha1SemaphoreHolding.semaphore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(holders, semaphore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SemaphoreHolding {\n");
    sb.append("    holders: ").append(toIndentedString(holders)).append("\n");
    sb.append("    semaphore: ").append(toIndentedString(semaphore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

