/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha.DBSink;
import io.argoproj.workflow.v1alpha.HTTPSink;
import io.argoproj.workflow.v1alpha.JetStreamSink;
import io.argoproj.workflow.v1alpha.KafkaSink;
import io.argoproj.workflow.v1alpha.Log;
import io.argoproj.workflow.v1alpha.S3Sink;
import io.argoproj.workflow.v1alpha.STAN;
import io.argoproj.workflow.v1alpha.VolumeSink;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Sink
 */

public class Sink {
  public static final String SERIALIZED_NAME_DB = "db";
  @SerializedName(SERIALIZED_NAME_DB)
  private DBSink db;

  public static final String SERIALIZED_NAME_DEAD_LETTER_QUEUE = "deadLetterQueue";
  @SerializedName(SERIALIZED_NAME_DEAD_LETTER_QUEUE)
  private Boolean deadLetterQueue;

  public static final String SERIALIZED_NAME_HTTP = "http";
  @SerializedName(SERIALIZED_NAME_HTTP)
  private HTTPSink http;

  public static final String SERIALIZED_NAME_JETSTREAM = "jetstream";
  @SerializedName(SERIALIZED_NAME_JETSTREAM)
  private JetStreamSink jetstream;

  public static final String SERIALIZED_NAME_KAFKA = "kafka";
  @SerializedName(SERIALIZED_NAME_KAFKA)
  private KafkaSink kafka;

  public static final String SERIALIZED_NAME_LOG = "log";
  @SerializedName(SERIALIZED_NAME_LOG)
  private Log log;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_S3 = "s3";
  @SerializedName(SERIALIZED_NAME_S3)
  private S3Sink s3;

  public static final String SERIALIZED_NAME_STAN = "stan";
  @SerializedName(SERIALIZED_NAME_STAN)
  private STAN stan;

  public static final String SERIALIZED_NAME_VOLUME = "volume";
  @SerializedName(SERIALIZED_NAME_VOLUME)
  private VolumeSink volume;


  public Sink db(DBSink db) {
    
    this.db = db;
    return this;
  }

   /**
   * Get db
   * @return db
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DBSink getDb() {
    return db;
  }


  public void setDb(DBSink db) {
    this.db = db;
  }


  public Sink deadLetterQueue(Boolean deadLetterQueue) {
    
    this.deadLetterQueue = deadLetterQueue;
    return this;
  }

   /**
   * Get deadLetterQueue
   * @return deadLetterQueue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDeadLetterQueue() {
    return deadLetterQueue;
  }


  public void setDeadLetterQueue(Boolean deadLetterQueue) {
    this.deadLetterQueue = deadLetterQueue;
  }


  public Sink http(HTTPSink http) {
    
    this.http = http;
    return this;
  }

   /**
   * Get http
   * @return http
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HTTPSink getHttp() {
    return http;
  }


  public void setHttp(HTTPSink http) {
    this.http = http;
  }


  public Sink jetstream(JetStreamSink jetstream) {
    
    this.jetstream = jetstream;
    return this;
  }

   /**
   * Get jetstream
   * @return jetstream
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JetStreamSink getJetstream() {
    return jetstream;
  }


  public void setJetstream(JetStreamSink jetstream) {
    this.jetstream = jetstream;
  }


  public Sink kafka(KafkaSink kafka) {
    
    this.kafka = kafka;
    return this;
  }

   /**
   * Get kafka
   * @return kafka
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public KafkaSink getKafka() {
    return kafka;
  }


  public void setKafka(KafkaSink kafka) {
    this.kafka = kafka;
  }


  public Sink log(Log log) {
    
    this.log = log;
    return this;
  }

   /**
   * Get log
   * @return log
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Log getLog() {
    return log;
  }


  public void setLog(Log log) {
    this.log = log;
  }


  public Sink name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Sink s3(S3Sink s3) {
    
    this.s3 = s3;
    return this;
  }

   /**
   * Get s3
   * @return s3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public S3Sink getS3() {
    return s3;
  }


  public void setS3(S3Sink s3) {
    this.s3 = s3;
  }


  public Sink stan(STAN stan) {
    
    this.stan = stan;
    return this;
  }

   /**
   * Get stan
   * @return stan
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public STAN getStan() {
    return stan;
  }


  public void setStan(STAN stan) {
    this.stan = stan;
  }


  public Sink volume(VolumeSink volume) {
    
    this.volume = volume;
    return this;
  }

   /**
   * Get volume
   * @return volume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public VolumeSink getVolume() {
    return volume;
  }


  public void setVolume(VolumeSink volume) {
    this.volume = volume;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sink githubComArgoprojLabsArgoDataflowApiV1alpha1Sink = (Sink) o;
    return Objects.equals(this.db, githubComArgoprojLabsArgoDataflowApiV1alpha1Sink.db) &&
        Objects.equals(this.deadLetterQueue, githubComArgoprojLabsArgoDataflowApiV1alpha1Sink.deadLetterQueue) &&
        Objects.equals(this.http, githubComArgoprojLabsArgoDataflowApiV1alpha1Sink.http) &&
        Objects.equals(this.jetstream, githubComArgoprojLabsArgoDataflowApiV1alpha1Sink.jetstream) &&
        Objects.equals(this.kafka, githubComArgoprojLabsArgoDataflowApiV1alpha1Sink.kafka) &&
        Objects.equals(this.log, githubComArgoprojLabsArgoDataflowApiV1alpha1Sink.log) &&
        Objects.equals(this.name, githubComArgoprojLabsArgoDataflowApiV1alpha1Sink.name) &&
        Objects.equals(this.s3, githubComArgoprojLabsArgoDataflowApiV1alpha1Sink.s3) &&
        Objects.equals(this.stan, githubComArgoprojLabsArgoDataflowApiV1alpha1Sink.stan) &&
        Objects.equals(this.volume, githubComArgoprojLabsArgoDataflowApiV1alpha1Sink.volume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(db, deadLetterQueue, http, jetstream, kafka, log, name, s3, stan, volume);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sink {\n");
    sb.append("    db: ").append(toIndentedString(db)).append("\n");
    sb.append("    deadLetterQueue: ").append(toIndentedString(deadLetterQueue)).append("\n");
    sb.append("    http: ").append(toIndentedString(http)).append("\n");
    sb.append("    jetstream: ").append(toIndentedString(jetstream)).append("\n");
    sb.append("    kafka: ").append(toIndentedString(kafka)).append("\n");
    sb.append("    log: ").append(toIndentedString(log)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    s3: ").append(toIndentedString(s3)).append("\n");
    sb.append("    stan: ").append(toIndentedString(stan)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

