/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.*;

/**
 * StripeEventSource
 */

public class StripeEventSource {
  public static final String SERIALIZED_NAME_API_KEY = "apiKey";
  @SerializedName(SERIALIZED_NAME_API_KEY)
  private V1SecretKeySelector apiKey;

  public static final String SERIALIZED_NAME_CREATE_WEBHOOK = "createWebhook";
  @SerializedName(SERIALIZED_NAME_CREATE_WEBHOOK)
  private Boolean createWebhook;

  public static final String SERIALIZED_NAME_EVENT_FILTER = "eventFilter";
  @SerializedName(SERIALIZED_NAME_EVENT_FILTER)
  private List<String> eventFilter = null;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Map<String, String> metadata = null;

  public static final String SERIALIZED_NAME_WEBHOOK = "webhook";
  @SerializedName(SERIALIZED_NAME_WEBHOOK)
  private WebhookContext webhook;


  public StripeEventSource apiKey(V1SecretKeySelector apiKey) {
    
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Get apiKey
   * @return apiKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1SecretKeySelector getApiKey() {
    return apiKey;
  }


  public void setApiKey(V1SecretKeySelector apiKey) {
    this.apiKey = apiKey;
  }


  public StripeEventSource createWebhook(Boolean createWebhook) {
    
    this.createWebhook = createWebhook;
    return this;
  }

   /**
   * Get createWebhook
   * @return createWebhook
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCreateWebhook() {
    return createWebhook;
  }


  public void setCreateWebhook(Boolean createWebhook) {
    this.createWebhook = createWebhook;
  }


  public StripeEventSource eventFilter(List<String> eventFilter) {
    
    this.eventFilter = eventFilter;
    return this;
  }

  public StripeEventSource addEventFilterItem(String eventFilterItem) {
    if (this.eventFilter == null) {
      this.eventFilter = new ArrayList<String>();
    }
    this.eventFilter.add(eventFilterItem);
    return this;
  }

   /**
   * Get eventFilter
   * @return eventFilter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getEventFilter() {
    return eventFilter;
  }


  public void setEventFilter(List<String> eventFilter) {
    this.eventFilter = eventFilter;
  }


  public StripeEventSource metadata(Map<String, String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public StripeEventSource putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<String, String>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getMetadata() {
    return metadata;
  }


  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public StripeEventSource webhook(WebhookContext webhook) {
    
    this.webhook = webhook;
    return this;
  }

   /**
   * Get webhook
   * @return webhook
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WebhookContext getWebhook() {
    return webhook;
  }


  public void setWebhook(WebhookContext webhook) {
    this.webhook = webhook;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StripeEventSource ioArgoprojEventsV1alpha1StripeEventSource = (StripeEventSource) o;
    return Objects.equals(this.apiKey, ioArgoprojEventsV1alpha1StripeEventSource.apiKey) &&
        Objects.equals(this.createWebhook, ioArgoprojEventsV1alpha1StripeEventSource.createWebhook) &&
        Objects.equals(this.eventFilter, ioArgoprojEventsV1alpha1StripeEventSource.eventFilter) &&
        Objects.equals(this.metadata, ioArgoprojEventsV1alpha1StripeEventSource.metadata) &&
        Objects.equals(this.webhook, ioArgoprojEventsV1alpha1StripeEventSource.webhook);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKey, createWebhook, eventFilter, metadata, webhook);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StripeEventSource {\n");
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    createWebhook: ").append(toIndentedString(createWebhook)).append("\n");
    sb.append("    eventFilter: ").append(toIndentedString(eventFilter)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    webhook: ").append(toIndentedString(webhook)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

