/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.v1alpha;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.v1alpha.Event;
import io.argoproj.workflow.v1alpha.Submit;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WorkflowEventBindingSpec
 */

public class WorkflowEventBindingSpec {
  public static final String SERIALIZED_NAME_EVENT = "event";
  @SerializedName(SERIALIZED_NAME_EVENT)
  private Event event;

  public static final String SERIALIZED_NAME_SUBMIT = "submit";
  @SerializedName(SERIALIZED_NAME_SUBMIT)
  private Submit submit;


  public WorkflowEventBindingSpec event(Event event) {
    
    this.event = event;
    return this;
  }

   /**
   * Get event
   * @return event
  **/
  @ApiModelProperty(required = true, value = "")

  public Event getEvent() {
    return event;
  }


  public void setEvent(Event event) {
    this.event = event;
  }


  public WorkflowEventBindingSpec submit(Submit submit) {
    
    this.submit = submit;
    return this;
  }

   /**
   * Get submit
   * @return submit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Submit getSubmit() {
    return submit;
  }


  public void setSubmit(Submit submit) {
    this.submit = submit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowEventBindingSpec ioArgoprojWorkflowV1alpha1WorkflowEventBindingSpec = (WorkflowEventBindingSpec) o;
    return Objects.equals(this.event, ioArgoprojWorkflowV1alpha1WorkflowEventBindingSpec.event) &&
        Objects.equals(this.submit, ioArgoprojWorkflowV1alpha1WorkflowEventBindingSpec.submit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(event, submit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowEventBindingSpec {\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    submit: ").append(toIndentedString(submit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

